#!/bin/bash

###############################################
# This script performs a quick check that
# the expected SMOG 2 environment is found
# and that the linked executables in fact
# return the same topology as is saved
# in the directory $(pwd)/share/test/benchmarks
###############################################


export smog2wrapper=`which smog2`
if [ -z "$smog2wrapper" ]
then
	echo "

' $> which smog2 ' returned null, which means smog2 is not configured correctly. 

Edit and source the file configure.smog2 

SMOG 2 not configured!  QUITTING
"
	exit 1
fi

export perl4smog=`tail -n 1 $smog2wrapper | awk '{print $1}'`

export SMOG_PATH=`tail -n 1 $smog2wrapper | awk '{print $2}' | sed "s/src\/smogv2$//g"`

count=0
if [ -z "$SMOG_PATH" ]; then
	echo "ERROR: smog2 wrapper executable \$smog2wrapper is not found"
	echo "Usually this means something is wrong with how configure.smog2 was sourced"
	exit 1
fi

echo "Found smog2 ... running basic tests ..." 

tmpDir=test-config-tmp
testDir=$(pwd)/share/test

for pdb in 1AKEapo_v2 1ypa.2chains 2GIS_noSAM_v2
do
	for graining in AA CA AAgauss
	do
		if [ -e $testDir/benchmarks/$pdb.$graining.pdb ]
		then
			echo "test: $pdb $graining"
			if [ -d $tmpDir ]
			then
				rm -r $tmpDir
			fi
			mkdir $tmpDir
			
			if [ $graining == "AA" ]
			then
				grainingText="AA"
			elif [ $graining == "CA" ]
			then
				grainingText="CA"
			elif [ $graining == "AAgauss" ]
			then
				grainingText="t $SMOG_PATH/share/templates/SBM_AA+gaussian"
			fi
			
			$perl4smog $smog2wrapper -i $testDir/benchmarks/$pdb.$graining.pdb -$grainingText -dname $tmpDir/$pdb.$graining  &> $tmpDir/smog2.output
			$perl4smog $testDir/benchmark.pl $testDir/benchmarks/$pdb.$graining.top $tmpDir/$pdb.$graining.top &> $tmpDir/$pdb.$graining.test
			
			a=$(grep ERROR $tmpDir/$pdb.$graining.test | wc -l | awk '{print $1}')
			b=$(grep "Your Structure-based Model is ready" $tmpDir/smog2.output | wc -l | awk '{print $1}')
			
			if [ $a -gt 0 ]
			then
				echo There are errors. Check $tmpDir/$pdb.$graining.test for details.
				exit 1
			elif [ $b -eq 0 ]
			then
				echo SMOG2 did not finish running. Check $tmpDir/smog.output for details.
			exit 1
			fi
		fi
	
	done
done
rm -r test-config-tmp
echo "Configuration check passed."
echo "------------------------"
echo "Configuration summary:"
echo "------------------------"
echo smog2 executable: $smog2wrapper
echo path to perl: $perl4smog
echo smog path: $SMOG_PATH

exit 0
