FROM --platform=$BUILDPLATFORM ubuntu:22.04
CMD ["bash"]
ENV PATH=/opt/smog2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV TZ=Europe/Kiev
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone # buildkit
RUN apt-get update && \
	apt-get upgrade -y && \
	apt-get install -y --no-install-recommends cpanminus vim git-all patch make cmake pdl default-jre libxml-simple-perl nano emacs && \
	cpanm String::Util Exporter XML::Validator::Schema && \
	rm -rf /root/.cpanm && \
	rm -rf /var/lib/apt/lists/* && \
	mkdir /opt/smog2 && \
	git clone -n https://github.com/smog-server/SMOG2.git /opt/smog2 && \
	cd /opt/smog2 && \
	git checkout tags/v2.4.5  && \
	rm -rf /opt/smog2/.git && \
	mkdir /workdir && \
	useradd -rm -d /home/smoguser -s /bin/bash -g root -G sudo -u 1001 smoguser -p "$(openssl passwd -1 smoguser)" && \
	chown -R smoguser /opt/* 
USER smoguser
WORKDIR /home/smoguser
RUN cd /opt/smog2 && perl4smog=/usr/bin/perl smog2dir=/opt/smog2 bash /opt/smog2/configure.smog2
