#!/usr/bin/perl -w
use strict;
use warnings;
use Carp;

print <<EOT;
*****************************************************************************************
                                       smog_removeH                                   

     smog_removeH is part of the SMOG v2 distribution, available at smog-server.org     

    This tool will remove all Hydrogen atoms from a PDB file.  This is a simple script,
 	  which assumes only ATOM, TER, and END lines appear in your PDB file.

  	  See the SMOG manual for usage guidelines for tabulated interactions.

           For questions regarding this script, contact info\@smog-server.org              
*****************************************************************************************
EOT

##
# STRIP HYDROGENS OFF PDB FILE 
# WARNING: THIS SCRIPT IS NOT COMPREHENSIVE, BUT CAN BE HELPFUL


if(scalar(@ARGV) != 1){
        confess("\nUsage: smog_removeH <PDB>\n");
}


my $pdb = $ARGV[0];
open(PDB,$pdb);
if (-e "$pdb.new"){confess "\n\nOutput file $pdb.new already exists.  Quitting.\n\n";}
open(PDBOUT,">$pdb.new");

my $atomCount = 0;
while(my $line = <PDB>)
{
   if($line =~ m/TER/){print PDBOUT $line;next;}
   if($line =~ m/END/){print PDBOUT "END";last;}
   if($line !~ m/^ATOM/){confess("$pdb is not structured properly\n");}

   my $atom = substr($line,12,4);
   $atom =~ s/^\s+//; #remove leading spaces
   $atom =~ s/\s+$//; #remove trailing spacesi
   if($atom =~ m/^H/) {next;}
   $atomCount++;
   my $putString = sprintf('%5s',$atomCount);
   substr($line,6,5,$putString);
   print PDBOUT $line;




}







